"use client";

import React, { lazy, Suspense, memo, useState, useCallback } from "react";
import {
  LayoutDashboard,
    TrendingUp,
      Users,
        DollarSign,
          Activity,
            Menu,
            } from "lucide-react";
            import {
              Chart as ChartJS,
                CategoryScale,
                  LinearScale,
                    PointElement,
                      LineElement,
                        BarElement,
                          ArcElement,
                            Tooltip,
                              Legend,
                              } from "chart.js";

                              ChartJS.register(
                                CategoryScale,
                                  LinearScale,
                                    PointElement,
                                      LineElement,
                                        BarElement,
                                          ArcElement,
                                            Tooltip,
                                              Legend
                                              );

                                              const Line = lazy(() =>
                                                import("react-chartjs-2").then((mod) => ({ default: mod.Line }))
                                                );
                                                const Bar = lazy(() =>
                                                  import("react-chartjs-2").then((mod) => ({ default: mod.Bar }))
                                                  );
                                                  const Doughnut = lazy(() =>
                                                    import("react-chartjs-2").then((mod) => ({ default: mod.Doughnut }))
                                                    );

                                                    const sampleData = {
                                                      monthlyRevenue: {
                                                          labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
                                                              datasets: [
                                                                    {
                                                                            label: "Revenue ($)",
                                                                                    data: [12000, 19000, 15000, 21000, 24000, 28000],
                                                                                            borderColor: "rgb(75, 192, 192)",
                                                                                                    backgroundColor: "rgba(75, 192, 192, 0.2)",
                                                                                                            fill: true,
                                                                                                                    tension: 0.4,
                                                                                                                          },
                                                                                                                              ],
                                                                                                                                },
                                                                                                                                  userSignups: {
                                                                                                                                      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
                                                                                                                                          datasets: [
                                                                                                                                                {
                                                                                                                                                        label: "New Users",
                                                                                                                                                                data: [200, 450, 350, 520, 480, 610],
                                                                                                                                                                        backgroundColor: "rgba(54, 162, 235, 0.7)",
                                                                                                                                                                              },
                                                                                                                                                                                  ],
                                                                                                                                                                                    },
                                                                                                                                                                                      expenseBreakdown: {
                                                                                                                                                                                          labels: ["Salaries", "Marketing", "Infrastructure", "Others"],
                                                                                                                                                                                              datasets: [
                                                                                                                                                                                                    {
                                                                                                                                                                                                            data: [45000, 22000, 12000, 8000],
                                                                                                                                                                                                                    backgroundColor: ["#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0"],
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                  recentTransactions: [
                                                                                                                                                                                                                                      { id: 1, customer: "Alice Johnson", amount: "$1,200", status: "Completed", date: "2026-05-10" },
                                                                                                                                                                                                                                          { id: 2, customer: "Bob Smith", amount: "$850", status: "Pending", date: "2026-05-09" },
                                                                                                                                                                                                                                              { id: 3, customer: "Carol White", amount: "$2,300", status: "Completed", date: "2026-05-08" },
                                                                                                                                                                                                                                                  { id: 4, customer: "Dave Lee", amount: "$430", status: "Failed", date: "2026-05-07" },
                                                                                                                                                                                                                                                      { id: 5, customer: "Eva Brown", amount: "$1,750", status: "Completed", date: "2026-05-06" },
                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                        const FinTechDashboard = memo(function FinTechDashboard() {
                                                                                                                                                                                                                                                          const [sidebarOpen, setSidebarOpen] = useState(true);
                                                                                                                                                                                                                                                            const toggleSidebar = useCallback(() => setSidebarOpen((prev) => !prev), []);

                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                  <div className="flex h-screen bg-gray-100">
                                                                                                                                                                                                                                                                        {/* Skip‑to‑content link */}
                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                      href="#main-content"
                                                                                                                                                                                                                                                                                              className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded focus:bg-white focus:px-4 focus:py-2 focus:text-blue-700 focus:shadow-lg focus:outline-none"
                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                            Skip to main content
                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                        {/* Sidebar */}
                                                                                                                                                                                                                                                                                                                              <aside
                                                                                                                                                                                                                                                                                                                                      aria-label="Primary navigation"
                                                                                                                                                                                                                                                                                                                                              className={`${sidebarOpen ? "w-64" : "w-20"} flex flex-col bg-blue-900 p-4 text-white transition-all duration-300`}
                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                            <div className="mb-8 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                      {sidebarOpen && <span className="text-xl font-bold" aria-hidden="true">FinDash</span>}
                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                        onClick={toggleSidebar}
                                                                                                                                                                                                                                                                                                                                                                                                                    aria-label={sidebarOpen ? "Collapse sidebar" : "Expand sidebar"}
                                                                                                                                                                                                                                                                                                                                                                                                                                aria-expanded={sidebarOpen}
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded p-1 hover:bg-blue-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Menu size={20} aria-hidden="true" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <nav role="navigation" aria-label="Dashboard sections" className="flex-1 space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <SidebarItem icon={<LayoutDashboard size={18} />} text="Dashboard" active sidebarOpen={sidebarOpen} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <SidebarItem icon={<TrendingUp size={18} />} text="Analytics" sidebarOpen={sidebarOpen} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <SidebarItem icon={<Users size={18} />} text="Customers" sidebarOpen={sidebarOpen} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SidebarItem icon={<DollarSign size={18} />} text="Revenue" sidebarOpen={sidebarOpen} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <SidebarItem icon={<Activity size={18} />} text="Reports" sidebarOpen={sidebarOpen} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Main content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <main id="main-content" aria-label="FinTech dashboard" tabIndex={-1} className="flex-1 overflow-y-auto p-6 focus-visible:outline-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* KPI cards */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section aria-label="Key performance indicators">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <StatCard title="Total Users" value="12,480" change="+12.5%" icon={<Users size={20} aria-hidden="true" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <StatCard title="Revenue" value="$48,500" change="+8.2%" icon={<DollarSign size={20} aria-hidden="true" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <StatCard title="Transactions" value="1,823" change="+15.3%" icon={<Activity size={20} aria-hidden="true" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <StatCard title="Growth" value="23.6%" change="+5.1%" icon={<TrendingUp size={20} aria-hidden="true" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Revenue + Expense charts */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section aria-label="Revenue and expense charts" className="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="rounded-lg bg-white p-4 shadow lg:col-span-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="mb-4 text-lg font-semibold text-gray-800">Monthly Revenue</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Suspense fallback={<ChartSkeleton label="Monthly Revenue" />}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Line data={sampleData.monthlyRevenue} options={{ responsive: true }} aria-label="Monthly revenue line chart" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Suspense>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-lg bg-white p-4 shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="mb-4 text-lg font-semibold text-gray-800">Expense Breakdown</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Suspense fallback={<ChartSkeleton label="Expense Breakdown" />}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Doughnut data={sampleData.expenseBreakdown} options={{ responsive: true }} aria-label="Expense breakdown doughnut chart" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Suspense>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* User signups chart */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section aria-label="User signups chart" className="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-lg bg-white p-4 shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="mb-4 text-lg font-semibold text-gray-800">User Signups</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Suspense fallback={<ChartSkeleton label="User Signups" />}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Bar data={sampleData.userSignups} options={{ responsive: true }} aria-label="User signups bar chart" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Suspense>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Recent transactions */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section aria-label="Recent transactions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-lg bg-white p-4 shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="mb-4 text-lg font-semibold text-gray-800">Recent Transactions</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div role="region" aria-label="Transactions table, scroll right to see all columns" className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table className="min-w-full text-left text-sm" aria-label="Recent 